# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/sources/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"


# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    # Install your package in editable mode with optional dev extras
    - method: pip
      path: "."
      extra_requirements:
        - docs
        - install
        - numba